### PR TITLE
Feature/new template

### PR DESCRIPTION
**Pull request by niklibrato**
Oh oops... I shipped a fix to a branch that has already been merged before.. will this work?

### CODE REVIEW

**Comment by obfuscurity** [comment]
@niklibrato can we kill this or do you still need it?

**Comment by niklibrato** [comment]
wait - this wasn't merged in? Would it help if we killed this and I created a new branch with all the changes?

**Comment by niklibrato** [comment]
actually.. the logo has changed again since then. Probably better if I revisit this.

**Comment by obfuscurity** [comment]
@niklibrato Ok if we close this and revisit again later?

**Comment by niklibrato** [comment]
close it. I saved the template here https://gist.github.com/niklibrato/3beecb624252ab46c037

**Pull request closed without merging**
