### PR TITLE
Add AWS SNS integration.

### PR DESCRIPTION
**Pull request by pouellet**
Here's a contribution for Issue #35. 

It requires as input:
* The ARN of the SNS Topic to publish to. (`topic_arn`)
* An access key id and secret (`access_key_id`, `secret_access_key`). The IAM user must be allowed to perform SNS:Publish action against the topic.

I used the same structure as the webhook service for the content of the message to keep consistency. I thought about creating a helper for it but didn't want to change to many things in the other services.

The schema of the payload for the `receive_alert_clear` is not defined in the helpers so I used the alert_payload to initialize the service in the test.

The `receive_validate` does not validate that the provided topic actually exists as it would require the user to have more permissions (list_topics or topic_attributes).

I added rspec to the Gemfile to benefit from it's mocking features but included it only as standalone so as not to conflict with the other tests.

### CODE REVIEW

**Comment by obfuscurity** [comment]
Very cool. Nice to see all the tests. Looks like at least a couple of them are failing on inconsistent ordering of hash keys. Can you fix those up for a clean test build?

**Comment by pouellet** [comment]
The test failed because my branch was out of sync with master, but comparing on hash is going to be more reliable. Should be good now.

**Comment by obfuscurity** [comment]
This looks solid. I'll need to play with this in a test environment and hook up the front-end bits, but I think it's ok to merge now. Thanks so much for your work on this!

**Comment by pouellet** [comment]
Thanks, I look forward to the UI integration. :+1:

Let me know if you need someone to test the end product.

**Comment by obfuscurity** [comment]
@pouellet I'm going to temporarily revert the merge so we can continue testing against your branch without blocking development elsewhere.

**Pull request merged**
