### PR TITLE
Update Slack snapshot payload

### PR DESCRIPTION
**Pull request by adamyonk**

### CODE REVIEW

**Comment by obfuscurity** [comment]
@adamyonk Just curious, what was the reason for the change here?

**Comment by adamyonk** [comment]
There wasn't really a place for the snapshot message field in the custom payload they had set up for us. The new standard webhook attachment payload has all the fields we need.

**Comment by obfuscurity** [comment]
Makes sense, thanks for the explanation. :sparkles:

**Comment by adamyonk** [comment]
:+1:

**Pull request merged**
