### PR TITLE
Set BigPanda primary_property to check name

### PR DESCRIPTION
**Pull request by akahn**
This will improve event correlation in BigPanda.

### CODE REVIEW

**Comment by obfuscurity** [comment]
Are you going to omit the `service` tag in this PR or separately?

**Comment by obfuscurity** [comment]
LGTM otherwise.

**Comment by obfuscurity** [comment]
test comment

**Comment by akahn** [comment]
> Are you going to omit the service tag in this PR or separately?

Okay, the service attribute is now removed.

**Pull request merged**
