### PR TITLE
OpsGenie: service to work with the new integration

### PR DESCRIPTION
**Pull request by halitokumus**
OpsGenie will take librato notifications through
api.opsgenie.com/v1/json/librato from now on, with settings: apiKey,
recipients, teams, tags.

Thanks for any help
Halit

### CODE REVIEW

**Comment by obfuscurity** [comment]
Thanks for this new version, I'll try to take a look at this today or tomorrow.

**Comment by halitokumus** [comment]
We have deployed the new integration at OpsGenie; it should work when this script is run. How does the script look; should we do a test?

**Comment by obfuscurity** [comment]
This is a pretty significant change. Is this new https://api.opsgenie.com/v1/json/librato endpoint documented publicly?

**Comment by halitokumus** [comment]
Yes; I mean it has been deployed to production, ready to accept the new script's requests. It also works backward-compatible so the current users won't be affected.

**Comment by halitokumus** [comment]
If you could sign up to OpsGenie, I can make the integration available to you so we can test it

**Comment by obfuscurity** [comment]
@halitokumus I was just hoping to better understand your API endpoint so we can vet these changes before merging.

I have one project in front of this one on my plate at the moment. Hopefully I'll be done with that today and able to dedicate my focus to this service tomorrow. :smile_cat:

**Comment by halitokumus** [comment]
The API endpoint is Librato specific.  We take the payload from Librato alert, and expose the fields in the configuration UI so that users can design their own alerts.  
We've designed the integration on our side in a way that it uses the same data available from a Librato webhook (plus the alert configuration data from Librato UI). 
I think the best way to understand the API endpoint is to take a look at the configuration UI as it shows how the data is processed. 
librato-integration-conditions
librato-integration-config

**Comment by halitokumus** [comment]
Also, OpsGenie has a newer logo; could you update the logo in the Notification Services page as well?

opsgenie

**Comment by halitokumus** [comment]
Hi @obfuscurity , how did it go? Is there anything we can help with; we want to do marketing based on this integration

**Comment by obfuscurity** [comment]
Sorry @halitokumus I haven't forgotten about you, it's just been really busy lately. I'm traveling this week but I'll try to dig into this as I have time.

**Comment by obfuscurity** [comment]
@halitokumus In order to remain backwards compatible with existing saved customer integrations, you probably want to keep referring to `customer_key` even though you're changing the POST to `api_key`. Does this make sense?

**Comment by halitokumus** [comment]
yes; do you mean I should do a "get api_key, if it doesn't exist then try
customer_key" routine? I'll take a look and commit a fix.
Thanks

**Comment by halitokumus** [comment]
I'll keep using customer_key for backward compatibility. It should be shown as "API key" on Librato UI, though.

**Comment by obfuscurity** [comment]
@halitokumus That seems to work well in our staging environment now. However, I'm not seeing a lot of detail coming through the payload using a "standard" OpsGenie API key. The runbook_url is there, but outside of that I'm not seeing anything useful. Should I be using a different type of key?

**Comment by halitokumus** [comment]
did you add a Librato integration in OpsGenie?  what's your customer name, I can take a look.

**Comment by obfuscurity** [comment]
@halitokumus I actually used an API integration on your end. Should I use the API token derived from an "OpsGenie Librato" (webhook) integration instead?

**Comment by halitokumus** [comment]
yes; you should add a Librato integration here https://www.opsgenie.com/integration?add=Librato and use its Api key; that's how we're going to document the instructions.

**Comment by obfuscurity** [comment]
Ok, that one looks a lot better. The existing user experience is pretty confusing right now because there are around 5 permutations of working + "broken" ways to configure this if you're not careful. :stuck_out_tongue: 

I'm going to take a deeper dive into the code before merging, but assuming we get this in soon, how long until you're able to update your UI and docs on your side?

**Comment by obfuscurity** [comment]
Just to confirm *one last time*, both of the following legacy setup paths will continue to be supported for backwards compatibility?

### The "OpsGenie Way"
1) Customer "A" added a "Librato integration" in the OpsGenie integrations page. They took the provided webhook URL and added that as a Webhook service integration over at Librato.

### The "Librato Way"
2) Customer "B" added an "API integration" in the OpsGenie integration page. They took the provided token and used that to create a new OpsGenie service integration over at Librato.

### Moving Forward
With the pending change, Customer A would appear to be the most affected. Previously they used OpsGenie's "Librato" integration to generate a **webhook**. Going forward, the **token** generated for that webhook will be the string used as the **API key** in our native Librato "OpsGenie" service integration, instead of the key previously generated as part of OpsGenie's API integration.

Confused yet? :smile_cat:

**Comment by halitokumus** [comment]
I updated the UI and doc; you can check https://www.opsgenie.com/integration?add=Librato and http://www.opsgenie.com/docs/integrations/librato-integration
I used "API key" in the instructions for the token field's new label on Librato; is that OK?

New Librato integration will have backward-compatible support for both the old ways you mentioned; yes.

Also on "account settings" page, the OpsGenie logo is outdated. I'm attaching a 70x70 logo; can you update that page, too? 
I'm also attaching the logo we can use on the new "Alerts" page.
opsgenie-70x70
opsgenie

**Comment by obfuscurity** [comment]
@halitokumus I should be able to get the new service merged and deployed today. I'll also get the field names changed to "API key". It might take a few days to update the logos, I've asked our design team to work on those.

**Comment by obfuscurity** [comment]
@halitokumus I'm testing this one last time before merging and none of the test alerts seem to be making it to my OpsGenie account. Want me to shoot you an email with the details?

**Comment by halitokumus** [comment]
Of course, you can e-mail me at halit.okumus@ifountain.com

**Comment by obfuscurity** [comment]
@halitokumus Thanks for the sanity check, I think we're good to go now.

**Comment by obfuscurity** [comment]
This has been shipped to production. I'll update our support docs tomorrow.

**Comment by halitokumus** [comment]
Thanks, Jason; there is one thing, though. The new UI should provide
configuration for "Teams" and "Tags" in addition to "Recipients".

Halit

**Comment by obfuscurity** [comment]
@halitokumus Sorry, I missed the addition of teams and tags. I'll look at this today.

**Comment by obfuscurity** [comment]
@halitokumus I think I have a working version in staging. Note that if an existing alert (in OpsGenie) receives a new incident (e.g. the count increases) with **new tags**, they don't show up on the existing alert. I had to close out the alert and send a new alert before the tags were visible.

**Comment by obfuscurity** [comment]
Screenshot from a successful alert with tags.

screen shot 2015-03-20 at 10 47 03 am

**Comment by halitokumus** [comment]
That's correct; thank you. Increasing the count is the intended behaviour;
so for now that case is OK for us.

Halit

**Comment by obfuscurity** [comment]
@halitokumus Ok, I just shipped Teams and Tags support to production. Customers with existing OpsGenie integrations will need to recreate them to have the new fields available.

**Comment by halitokumus** [comment]
That sounds good. The UI also looks good; but I noticed that in the new
Alerts UI the label says "customer key" for the API key field. We actually
prefer to use "API key"; it would be better if we lose the "customer key"
expression; we don't use it anymore.

Thanks

**Comment by obfuscurity** [comment]
That label change is live in production now.

**Pull request merged**
